version: '3.4'

services:
  web:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
    links:
      - php

  php:
    image: php:8-fpm

  mailhog:
    image: mailhog/mailhog
    logging:
      driver: 'none'  # disable saving logs
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui

  composer:
    image: composer/composer
    volumes:
      - ../:/app
    command: install